FROM node:24.5.0-slim AS builder

RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

WORKDIR /home/soraai

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --network-timeout 600000

COPY tsconfig.json next.config.mjs next-env.d.ts postcss.config.js drizzle.config.ts tailwind.config.ts ./
COPY src ./src
COPY public ./public
COPY src/lib/db/migrations ./src/lib/db/migrations

RUN yarn build

FROM node:24.5.0-slim

RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

WORKDIR /home/soraai

COPY --from=builder /home/soraai/public ./public
COPY --from=builder /home/soraai/.next/static ./public/_next/static

COPY --from=builder /home/soraai/.next/standalone ./
COPY --from=builder /home/soraai/src/lib/db/migrations ./src/lib/db/migrations

RUN mkdir /home/soraai/uploads

EXPOSE 3000

CMD ["node", "server.js"]
